#!/bin/bash
mkdir cartellaProvvisoria
cd cartellaProvvisoria
ask clone -s amzn1.ask.skill.7e1717eb-d504-4edf-87c7-19e0fb9ca498
cd ..
node daily_script_codiceJS.js
cd cartellaProvvisoria/InformationPoint
ask deploy
cd ../..
rm -r cartellaProvvisoria
# additionalDailyDestinations: workshop archea,algebra e analisi numerica,serena morigi,morigi,analisi numerica,elaborazione dei segnali,marco chiani,chiani,andrea giorgetti,giorgetti,istituzioni di matematiche,marco lenci,lenci,preveniamo,iniziativa preveniamo, rivolta agli studenti universitari,ricerca operativa,roberto baldacci,baldacci,sensori e nanotecnologie,marco tartagni,tartagni,sistemi elettronici e sensori  (c.i.) - sensori e attuatori,sistemi elettronici e sensori  (c.i.),sistemi elettronici e sensori,fondamenti di biomeccanica,rita stagni,stagni,programmazione ad oggetti,mirko viroli,viroli,linguaggi, compilatori e modelli computazionali,mario bravetti,bravetti,storia  e restauro (c.i.) - storia dell'architettura 3,storia  e restauro (c.i.),storia  e restauro,matteo cassani simonetti,simonetti,storia  e restauro (c.i.) - teorie e storia del restauro,marco pretelli,pretelli,conversione elettromeccanica dell'energia,alberto bellini,bellini,data mining,matteo golfarelli,golfarelli,gianluca moro,moro,bioingegneria della riabilitazione,lorenzo chiari,chiari,diagnostica strutturale,lucio nobile,nobile,mario bonagura,bonagura,elementi di urbanistica,enrico brighi,brighi,fondamenti di chimica,nadia lotti,lotti,ingegneria del software,stefano rizzi,rizzi,matematica,programmazione - cl.b (cl.b),programmazione,alessandra lumini,lumini,sistemi elettronici e sensori  (c.i.) - sistemi elettronici,nicolo' attilio speciale,speciale,algoritmi di ottimizzazione,tutorato progetti fondamenti di biomeccanica,fisiologia,matteo cerri,cerri,speciale - sistemi elettronici  - ricevimento,geometria e algebra,michele mulazzani,mulazzani,sistemi operativi,vittorio ghini,ghini,programmazione (prof.ssa carbonaro),afpg - laboratorio di diagnostica strutturale,afpg,organi artificiali,emanuela marcelli,marcelli,scienza delle costruzioni,luisa molari,molari,veronica bartolomeo,bartolomeo,business intelligence,comunicazioni digitali e internet,davide dardari,dardari,colloquio candidati assegno di tutorato corsi di studio dei,callegati - gruppo tlc e informatica,callegati,psicologia della forma,emanuele valgiusti,valgiusti,elettronica,claudio fiegna,fiegna,biomateriali e comportamento meccanico dei biomateriali (c.i.) - biomateriali,biomateriali e comportamento meccanico dei biomateriali (c.i.),biomateriali e comportamento meccanico dei biomateriali,joseph lovecchio,lovecchio,alberto sensini,sensini